# Generated by Django 4.2.24 on 2025-10-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
        ('TresorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteagence',
            name='libelle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compteagence',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='MainApp.agence'),
        ),
    ]
