# Generated by Django 4.2.25 on 2025-10-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TresorApp', '0002_typeactivity_compteagence_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteagence',
            name='principal',
        ),
    ]
