# Generated by Django 4.2.24 on 2025-10-01 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0007_modaliteecheance_libelle2'),
        ('TresorApp', '0002_compteagence_libelle_alter_compteagence_agence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='numero',
            new_name='libelle',
        ),
        migrations.AddField(
            model_name='operation',
            name='transaction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='FinanceApp.transaction'),
            preserve_default=False,
        ),
    ]
