# Generated by Django 4.2.24 on 2025-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TresorApp', '0003_rename_numero_operation_libelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
