# Generated by Django 4.2.25 on 2026-02-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0009_pret_date_decaissement'),
        ('TresorApp', '0003_remove_compteagence_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='pret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='FinanceApp.pret'),
        ),
    ]
