# Generated by Django 4.2.24 on 2025-10-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0007_modaliteecheance_libelle2'),
        ('TresorApp', '0004_operation_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='FinanceApp.transaction'),
        ),
    ]
