# Generated by Django 4.2.25 on 2025-10-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TresorApp', '0005_alter_operation_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='compte_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='TresorApp.compteagence'),
        ),
    ]
