"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dw6*n0&2txrpe1il3@-a((%^hdfa75)bs$dmpwyx!l3!j4!yz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", 'https://www.assana-services.com']
CSRF_TRUSTED_ORIGINS = ['https://www.assana-services.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "AuthentificationApp",
    "FinanceApp",
    "TresorApp",
    "MainApp",
    "StatsApp",
    "CoreApp",
    
    "django_crontab",
    "mathfilters"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    
    # 'default': {
    #     'ENGINE'    : 'django.db.backends.mysql',
    #     'HOST'      : os.getenv("DB_HOST", "77.237.237.101"),
    #     'PORT'      : os.getenv("DB_PORT", 3307),
    #     'USER'      : os.getenv("DB_USER", "root"),
    #     'PASSWORD'  : os.getenv("DB_PASSWORD", "1sd48ds5ds45"),
    #     'NAME'      : os.getenv("DB_NAME", "microcred"),
    # },
    
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'AuthentificationApp.Employe'
LOGIN_URL = 'AuthentificationApp:login'
LOGIN_REDIRECT_URL = 'MainApp:dashboard'
LOGOUT_REDIRECT_URL = 'AuthentificationApp:logout'

USE_THOUSAND_SEPARATOR = True
USE_TZ = True


CRONTAB_DJANGO_PROJECT_NAME = "Microcred"
CRONJOBS = [
    # chaque jour à minuit → calcul pénalités
    ('0 0 * * *', 'FinanceApp.crons.generer_penalites', '>> {}'.format(os.path.join(BASE_DIR, "logs/penelites.log" ))),

    # # chaque jour à 01h → calcul intérêts épargne
    ('0 1 * * *', 'FinanceApp.crons.generer_interets_epargnes', '>> {}'.format(os.path.join(BASE_DIR, "logs/interets.log" ))),
    
    
    # ('* * * * *', 'FinanceApp.crons.generer_penalites', '>> {}'.format(os.path.join(BASE_DIR, "logs/penelites.txt" ))),
    # ('* * * * *', 'FinanceApp.crons.generer_interets_epargnes', '>> {}'.format(os.path.join(BASE_DIR, "logs/interets.txt" ))),
]