# Generated by Django 4.2.25 on 2025-10-07 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FinanceApp', '0005_pret_interet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('numero', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('base', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('nombre', models.PositiveIntegerField(default=0)),
                ('frais', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('retire', models.BooleanField(default=False)),
                ('cleint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelis', to='MainApp.client')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FidelisCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('level', models.PositiveIntegerField(default=0)),
                ('fidelis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='FidelisApp.fidelis')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='FinanceApp.statuspret')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
