# Generated by Django 4.2.25 on 2025-10-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0005_pret_interet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0001_initial'),
        ('FidelisApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteFidelis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('numero', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('base', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('nombre', models.PositiveIntegerField(default=0)),
                ('frais', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('retire', models.BooleanField(default=False)),
                ('cleint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelis', to='MainApp.client')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelis', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelis', to='FinanceApp.statuspret')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fideliscase',
            name='fidelis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='FidelisApp.comptefidelis'),
        ),
        migrations.DeleteModel(
            name='Fidelis',
        ),
    ]
