# Generated by Django 4.2.25 on 2025-10-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FidelisApp', '0002_comptefidelis_alter_fideliscase_fidelis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptefidelis',
            old_name='cleint',
            new_name='client',
        ),
    ]
