# Generated by Django 4.2.25 on 2025-10-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0005_pret_interet'),
        ('FidelisApp', '0003_rename_cleint_comptefidelis_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptefidelis',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fidelis', to='FinanceApp.statuspret'),
        ),
    ]
