# Generated by Django 4.2.25 on 2025-10-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FidelisApp', '0004_alter_comptefidelis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptefidelis',
            name='cloture_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
