# Generated by Django 4.2.25 on 2025-10-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantie',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='garantie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='garanties/'),
        ),
        migrations.AddField(
            model_name='garantie',
            name='temoin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
