# Generated by Django 4.2.25 on 2025-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0002_garantie_contact_garantie_image_garantie_temoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='interet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='echeance',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
