# Generated by Django 4.2.24 on 2025-09-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0002_modepayement_alter_interet_compte_transaction_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
