# Generated by Django 4.2.24 on 2025-09-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0003_echeance_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echeance',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='compteepargne',
            name='modalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceApp.modaliteecheance'),
        ),
        migrations.AlterField(
            model_name='compteepargne',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compteepargne',
            name='solde_actuel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='compteepargne',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceApp.statuspret'),
        ),
        migrations.AlterField(
            model_name='pret',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceApp.statuspret'),
        ),
    ]
