# Generated by Django 4.2.25 on 2025-10-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0004_typeamortissement_pret_amortissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='interet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
