# Generated by Django 4.2.24 on 2025-09-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0004_remove_echeance_commentaire_compteepargne_modalite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteepargne',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pret',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
