# Generated by Django 4.2.24 on 2025-09-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FinanceApp', '0005_compteepargne_commentaire_pret_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='confirmateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_prets', to=settings.AUTH_USER_MODEL),
        ),
    ]
