# Generated by Django 4.2.25 on 2025-10-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FidelisApp', '0004_alter_comptefidelis_status'),
        ('FinanceApp', '0005_pret_interet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fidelis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='FidelisApp.comptefidelis'),
        ),
    ]
