# Generated by Django 4.2.25 on 2025-10-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0006_transaction_fidelis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
