# Generated by Django 4.2.24 on 2025-09-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0006_pret_confirmateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaliteecheance',
            name='libelle2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
