# Generated by Django 4.2.24 on 2025-10-01 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FinanceApp', '0007_modaliteecheance_libelle2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garanties', to=settings.AUTH_USER_MODEL)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garanties', to='FinanceApp.pret')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
