# Generated by Django 4.2.25 on 2025-11-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0007_pret_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
