# Generated by Django 4.2.25 on 2025-12-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0008_pret_date_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='date_decaissement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
