# Generated by Django 4.2.24 on 2025-10-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0008_garantie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garantie',
            old_name='valeur',
            new_name='montant',
        ),
    ]
