# Generated by Django 4.2.25 on 2025-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0009_rename_valeur_garantie_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='taux_penalite',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=5, null=True),
        ),
    ]
