# Generated by Django 4.2.25 on 2026-02-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0010_echeance_interet_paye_echeance_penalites_payees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='FinanceApp.pret'),
        ),
    ]
