# Generated by Django 4.2.24 on 2025-09-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='nom',
            new_name='libelle',
        ),
    ]
