# Generated by Django 4.2.24 on 2025-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0002_rename_nom_role_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
