# Generated by Django 4.2.24 on 2025-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='etiquette',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
