# Generated by Django 4.2.25 on 2025-10-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0003_employe_phrase_secrete_employe_reponse_secrete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='phrase_secrete',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='reponse_secrete',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
