# Generated by Django 4.2.24 on 2025-09-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0004_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
