# Generated by Django 4.2.24 on 2025-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthentificationApp', '0005_alter_employe_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='brut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
