# Generated by Django 4.2.24 on 2025-09-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(upload_to='rapports/')),
                ('type_rapport', models.CharField(max_length=50)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.agence')),
            ],
        ),
    ]
